# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# require_relative '../node_modules/react-native/scripts/react_native_pods'

# platform :ios, '10.0'

# dynamic_frameworks = ['CardVerify']

# target 'example' do
#   pod 'CardVerify', :http => 'https://api.getbouncer.com/v1/downloads/sdk/card_verify/<your_api_key_here>/cardverify-ios-1.0.5041-xcframework-release.tgz'
#   pod 'react-native-cardverify', :path => '../node_modules/react-native-cardverify/react-native-cardverify.podspec'

#   config = use_native_modules!
#   use_react_native!(:path => config["reactNativePath"])  

#   # Enables Flipper.
#   #
#   # Note that if you have use_frameworks! enabled, Flipper will not work and
#   # you should disable these next few lines.
#   use_flipper!
#   post_install do |installer|
#     flipper_post_install(installer)
#   end
# end

# pre_install do |installer|
#   installer.pod_targets.each do |pod|
#     if dynamic_frameworks.include?(pod.name)
#       puts "Overriding the build_as_static_framework? method for #{pod.name}"
#       def pod.build_as_static_framework?;
#         false
#       end
#     end
#   end
# end

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '11.2'
target 'example' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  permissions_path = '../node_modules/react-native-permissions/ios'
  # Pods for Cash
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'Firebase/Performance', '~> 6.3.0'
  # permissions
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'RNReactNativeHapticFeedback', :path => '../node_modules/react-native-haptic-feedback'
  # bouncer
  pod 'CardVerify', :http => 'https://api.getbouncer.com/v1/downloads/sdk/card_verify/1Zwkh7_YevJI2P4Oei440mYfiL6qcfAl/cardverify-ios-1.0.5041-xcframework-release.tgz'
  pod 'react-native-cardverify', :path => '../node_modules/react-native-cardverify/react-native-cardverify.podspec'
  pod 'jail-monkey', :path => '../node_modules/jail-monkey'
  dynamic_frameworks = ['CardVerify']
  pre_install do |installer|
  installer.pod_targets.each do |pod|
    if dynamic_frameworks.include?(pod.name)
      puts "Overriding the build_as_static_framework? method for #{pod.name}"
        def pod.build_as_static_framework?;
          false
        end
      end
    end
  end
  target 'CashTests' do
    inherit! :complete
    # Pods for testing
  end
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
target 'Cash-tvOS' do
  # Pods for Cash-tvOS
  target 'Cash-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

